Repository felangel/mocktail, pull requests merged in 2021-12, with the labels that each got.

#94 Fix expected value on documentation
  packages/mocktail/README.md
Labels: documentation

#67 feat!: support type args
  packages/mocktail/lib/src/_invocation_matcher.dart
  packages/mocktail/lib/src/_is_invocation.dart
  packages/mocktail/lib/src/_real_call.dart
  packages/mocktail/test/mockito_compat/invocation_matcher_test.dart
  packages/mocktail/test/mockito_compat/until_called_test.dart
  packages/mocktail/test/mockito_compat/verify_test.dart
Labels: enhancement

#97 refactor(mocktail): type arg support enhancements
  packages/mocktail/example/main.dart
  packages/mocktail/test/mockito_compat/invocation_matcher_test.dart
  packages/mocktail/test/mocktail_test.dart
Labels: refactor

#98 chore(mocktail): v0.3.0-dev.1
  packages/mocktail/CHANGELOG.md
  packages/mocktail/README.md
  packages/mocktail/example/main.dart
  packages/mocktail/example/pubspec.yaml
  packages/mocktail/pubspec.yaml
Labels: chore

#99 chore(mocktail_image_network): v0.3.0-dev.1
  packages/mocktail_image_network/CHANGELOG.md
  packages/mocktail_image_network/pubspec.yaml
Labels: chore, breaking change
