Repository felangel/mocktail, pull requests merged in 2021-03, with the labels that each got.

#18 fix: any matcher without value
  packages/mocktail/lib/src/mocktail.dart
  packages/mocktail/test/mocktail_test.dart
Labels: bug

#21 chore(mocktail): v0.0.1-dev.12
  packages/mocktail/CHANGELOG.md
  packages/mocktail/pubspec.yaml
Labels: chore

#23 Removed the `of` parameter of matchers in exchange for a `registerFallbackValue`
  packages/mocktail/lib/src/_register_matcher.dart
  packages/mocktail/test/matcher_test.dart
  packages/mocktail/test/mockito_compat/generated_mocks_test.dart
  packages/mocktail/test/mockito_compat/mockito_test.dart
  packages/mocktail/test/mockito_compat/until_called_test.dart
  packages/mocktail/test/mockito_compat/verify_test.dart
  packages/mocktail/test/mocktail_test.dart
Labels: enhancement

#26 feat(mocktail_image_network)!: upgrade to mocktail v0.0.2-dev.4
  packages/mocktail_image_network/CHANGELOG.md
  packages/mocktail_image_network/example/pubspec.yaml
  packages/mocktail_image_network/lib/src/mocktail_image_network.dart
  packages/mocktail_image_network/pubspec.yaml
Labels: chore

#27 fix(mocktail): verify use argmatcher from invocation when matcher is not provided
  packages/mocktail/CHANGELOG.md
  packages/mocktail/lib/src/_is_invocation.dart
  packages/mocktail/pubspec.yaml
  packages/mocktail/test/mocktail_test.dart
Labels: bug

#29 chore(mocktail): upgrade to test_api: ^0.3.0
  .github/workflows/mocktail.yaml
  packages/mocktail/CHANGELOG.md
  packages/mocktail/lib/src/_register_matcher.dart
  packages/mocktail/pubspec.yaml
  packages/mocktail/test/matcher_test.dart
  packages/mocktail/test/mockito_compat/invocation_matcher_test.dart
Labels: chore

#31 feat(mocktail): v0.1.0
  packages/mocktail/CHANGELOG.md
  packages/mocktail/lib/src/mocktail.dart
  packages/mocktail/pubspec.yaml
  packages/mocktail/test/mockito_compat/mockito_test.dart
  packages/mocktail/test/mocktail_test.dart
Labels: enhancement

#32 feat(mocktail_image_network): v0.1.0
  packages/mocktail_image_network/CHANGELOG.md
  packages/mocktail_image_network/pubspec.yaml
Labels: enhancement

#34 Add missing fallback value
  packages/mocktail/lib/src/_register_matcher.dart
  packages/mocktail/test/matcher_test.dart
Labels: enhancement

#33 docs: Fix 404 link
  packages/mocktail/lib/src/mocktail.dart
Labels: documentation, enhancement

#36 chore(mocktail): v0.1.1
  packages/mocktail/CHANGELOG.md
  packages/mocktail/pubspec.yaml
Labels: chore
