Repository felangel/mocktail, pull requests merged in 2023-12, with the labels that each got.

#220 chore(deps): allow `pkg:test_api >=0.7.0`
  packages/mocktail/pubspec.yaml
Labels: dependencies

#215 docs(mocktail): update `verify` example in `README.md`
  packages/mocktail/README.md
Labels: documentation

#222 chore(mocktail): v1.0.2
  packages/mocktail/CHANGELOG.md
  packages/mocktail/pubspec.yaml
Labels: chore
